const DEFAULT_CONTENT = {
  hero: { eyebrow: 'QASSEM.NET — DIGITAL SYSTEMS ARCHITECTURE', typeWords: ['Systems Architect','Cloud Engineer','Security Leader','Digital Strategist'], specializations: ['AI','Cloud','Cybersecurity','Data Science','Project Management','Computer Science'], subtitle: 'MBA Candidate', description: 'Designing secure systems where cloud infrastructure, cybersecurity, and strategy work together with clarity and purpose.', primaryButton: 'View Certifications →', primaryLink: '#certifications', secondaryButton: 'Contact Me', secondaryLink: '#contact' },
  stats: [{ value: 8, label: 'Certifications' },{ value: 12, label: 'Core Skills' },{ value: 2, label: 'Degrees' },{ value: 1, label: 'Domain' }],
  about: { title: 'From systems to strategy', paragraph1: 'I’m Kasem Adra, a systems architect focused on cloud infrastructure, cybersecurity, and digital strategy.', paragraph2: 'My work sits at the intersection of AI, cloud computing, cybersecurity, and transformation strategy.' },
  skills: [{ name: 'Cloud Architecture', level: 95 },{ name: 'Cybersecurity', level: 90 },{ name: 'DevSecOps', level: 88 },{ name: 'AI Systems', level: 82 },{ name: 'Digital Strategy', level: 92 },{ name: 'Data Science', level: 86 }],
  expertise: [{ icon:'◎', title:'AI Systems', description:'Architecting intelligent workflows, automation layers, and decision-support systems.' },{ icon:'☁', title:'Cloud Architecture', description:'Designing scalable, resilient, and secure cloud-native infrastructure.' },{ icon:'⬡', title:'Cybersecurity', description:'Embedding security controls, risk thinking, and operational defense into every layer.' }],
  certifications: ['SCCM','Windows Server Virtualization','CompTIA Cloud+','CompTIA Security+','DevOps Foundations','DevSecOps','Kubernetes','Cloud Architecture'],
  education: [{ title: 'Universidad Isabel I', description: 'MBA + Digital Marketing & Analytics' },{ title: 'European Business Institute of Luxembourg', description: 'Bachelor of Business Administration' }],
  projects: [], blog: [],
  contact: { title: 'Connect with Kasem', description: 'Available for consulting, systems architecture, cloud infrastructure, cybersecurity, and digital transformation projects.', links: [{ label:'info@qassem.net', url:'mailto:info@qassem.net' },{ label:'LinkedIn — Qassem Adra', url:'https://www.linkedin.com/in/qassem-adra/' }] },
  theme: { black:'#01040a', navy:'#06111e', emerald:'#34d399', cyan:'#a5f3fc', muted:'#93a4b8', text:'#f8fafc', cardBackground:'rgba(255,255,255,.035)', border:'rgba(255,255,255,.10)', glow:'rgba(52,211,153,.16)', buttonText:'#02050c', particleOpacity:1, glassBlur:18, radius:32, spacing:24, motion:1 }
};

const VERSION = 'enterprise-os-v3';
const enc = new TextEncoder();
const dec = new TextDecoder();
const JSON_HEADERS = {'content-type':'application/json; charset=utf-8','cache-control':'no-store'};
const SECURITY_HEADERS = {
  'x-content-type-options':'nosniff','x-frame-options':'DENY','referrer-policy':'strict-origin-when-cross-origin',
  'permissions-policy':'camera=(), microphone=(), geolocation=()','cross-origin-opener-policy':'same-origin'
};
function withSecurity(res){ const h=new Headers(res.headers); for(const [k,v] of Object.entries(SECURITY_HEADERS)) h.set(k,v); return new Response(res.body,{status:res.status,statusText:res.statusText,headers:h}); }
function json(data,status=200,headers={}){return new Response(JSON.stringify(data,null,2),{status,headers:{...JSON_HEADERS,...SECURITY_HEADERS,...headers}})}
function text(body,type='text/plain; charset=utf-8',status=200){return new Response(body,{status,headers:{'content-type':type,...SECURITY_HEADERS}})}
function adminPassword(env){return env.ADMIN_PASSWORD||env.PASSWORD||''}
function sessionSecret(env){return env.SESSION_SECRET||adminPassword(env)}
function safeName(name='file'){return String(name).replace(/[^a-z0-9_.-]+/gi,'-').replace(/-+/g,'-').slice(0,120)||'file'}
function clamp(v,min,max){v=Number(v)||0;return Math.max(min,Math.min(max,v))}
function b64url(input){const bytes=input instanceof Uint8Array?input:enc.encode(String(input));let s='';bytes.forEach(b=>s+=String.fromCharCode(b));return btoa(s).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
function b64urlDecode(v){v=v.replace(/-/g,'+').replace(/_/g,'/');while(v.length%4)v+='=';const bin=atob(v);const bytes=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)bytes[i]=bin.charCodeAt(i);return dec.decode(bytes)}
async function hmac(msg,secret){const key=await crypto.subtle.importKey('raw',enc.encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);return b64url(new Uint8Array(await crypto.subtle.sign('HMAC',key,enc.encode(msg))))}
async function sha256(value){return b64url(new Uint8Array(await crypto.subtle.digest('SHA-256',enc.encode(value))))}
function nowIso(){return new Date().toISOString()}
function ip(request){return request.headers.get('cf-connecting-ip')||request.headers.get('x-forwarded-for')||'local'}
function mergeDefaults(x){return {...DEFAULT_CONTENT,...(x||{}),hero:{...DEFAULT_CONTENT.hero,...(x?.hero||{})},about:{...DEFAULT_CONTENT.about,...(x?.about||{})},contact:{...DEFAULT_CONTENT.contact,...(x?.contact||{})},theme:{...DEFAULT_CONTENT.theme,...(x?.theme||{})}}}
async function ensureDb(env){if(!env.DB)return;const stmts=[
`CREATE TABLE IF NOT EXISTS settings (key TEXT PRIMARY KEY, value TEXT NOT NULL, updated_at TEXT DEFAULT CURRENT_TIMESTAMP)`,
`CREATE TABLE IF NOT EXISTS content_versions (id TEXT PRIMARY KEY, value TEXT NOT NULL, created_at TEXT DEFAULT CURRENT_TIMESTAMP, actor TEXT DEFAULT 'admin')`,
`CREATE TABLE IF NOT EXISTS snapshots (id TEXT PRIMARY KEY, label TEXT, value TEXT NOT NULL, created_at TEXT DEFAULT CURRENT_TIMESTAMP, actor TEXT DEFAULT 'admin')`,
`CREATE TABLE IF NOT EXISTS media (id TEXT PRIMARY KEY, filename TEXT NOT NULL, key TEXT NOT NULL, type TEXT, size INTEGER, url TEXT, alt TEXT, width INTEGER, height INTEGER, created_at TEXT DEFAULT CURRENT_TIMESTAMP)`,
`CREATE TABLE IF NOT EXISTS analytics_events (id TEXT PRIMARY KEY, path TEXT, referrer TEXT, user_agent TEXT, country TEXT, created_at TEXT DEFAULT CURRENT_TIMESTAMP)`,
`CREATE TABLE IF NOT EXISTS seo_settings (key TEXT PRIMARY KEY, value TEXT NOT NULL, updated_at TEXT DEFAULT CURRENT_TIMESTAMP)`,
`CREATE TABLE IF NOT EXISTS audit_logs (id TEXT PRIMARY KEY, action TEXT NOT NULL, metadata TEXT, ip TEXT, user_agent TEXT, created_at TEXT DEFAULT CURRENT_TIMESTAMP)`,
`CREATE TABLE IF NOT EXISTS sessions (id TEXT PRIMARY KEY, token_hash TEXT NOT NULL, role TEXT DEFAULT 'admin', expires_at INTEGER NOT NULL, revoked_at INTEGER, ip TEXT, user_agent TEXT, created_at TEXT DEFAULT CURRENT_TIMESTAMP)`,
`CREATE TABLE IF NOT EXISTS rate_limits (key TEXT PRIMARY KEY, count INTEGER NOT NULL, reset_at INTEGER NOT NULL)`,
`CREATE TABLE IF NOT EXISTS security_settings (key TEXT PRIMARY KEY, value TEXT NOT NULL, updated_at TEXT DEFAULT CURRENT_TIMESTAMP)`
];for(const s of stmts) await env.DB.prepare(s).run();}
async function audit(env,request,action,metadata={}){try{if(env.DB)await env.DB.prepare(`INSERT INTO audit_logs (id,action,metadata,ip,user_agent) VALUES (?,?,?,?,?)`).bind(crypto.randomUUID(),action,JSON.stringify(metadata),ip(request),request.headers.get('user-agent')||'').run()}catch{}}
async function rateLimit(env,key,limit=60,windowSec=60){if(!env.DB)return true;await ensureDb(env);const now=Date.now(), reset=now+windowSec*1000;const row=await env.DB.prepare(`SELECT count,reset_at FROM rate_limits WHERE key=?`).bind(key).first();if(!row||row.reset_at<now){await env.DB.prepare(`INSERT INTO rate_limits (key,count,reset_at) VALUES (?,?,?) ON CONFLICT(key) DO UPDATE SET count=excluded.count, reset_at=excluded.reset_at`).bind(key,1,reset).run();return true}if(row.count>=limit)return false;await env.DB.prepare(`UPDATE rate_limits SET count=count+1 WHERE key=?`).bind(key).run();return true}
async function createToken(env,request){const sid=crypto.randomUUID();const payload={sid,role:'admin',exp:Date.now()+12*60*60*1000,iat:Date.now()};const body=b64url(JSON.stringify(payload));const sig=await hmac(body,sessionSecret(env));const token=`${body}.${sig}`;if(env.DB)await env.DB.prepare(`INSERT INTO sessions (id,token_hash,role,expires_at,ip,user_agent) VALUES (?,?,?,?,?,?)`).bind(sid,await sha256(token),'admin',payload.exp,ip(request),request.headers.get('user-agent')||'').run();return token}
async function verifyToken(token,env){if(!token||!token.includes('.')||!sessionSecret(env))return null;const [body,sig]=token.split('.');if(sig!==await hmac(body,sessionSecret(env)))return null;let p;try{p=JSON.parse(b64urlDecode(body))}catch{return null}if(p.role!=='admin'||Date.now()>p.exp)return null;if(env.DB&&p.sid){await ensureDb(env);const row=await env.DB.prepare(`SELECT revoked_at,expires_at FROM sessions WHERE id=? AND token_hash=?`).bind(p.sid,await sha256(token)).first();if(!row||row.revoked_at||Date.now()>row.expires_at)return null}return p}
async function requireAdmin(request,env){const header=request.headers.get('x-admin-password')||'';if(adminPassword(env)&&header===adminPassword(env))return {role:'admin',method:'password-header'};const auth=(request.headers.get('authorization')||'').replace(/^Bearer\s+/i,'').trim();const p=await verifyToken(auth,env);if(p)return p;const m=(request.headers.get('cookie')||'').match(/qassem_session=([^;]+)/);return m?await verifyToken(m[1],env):null}
async function getContent(env){await ensureDb(env);if(!env.DB)return DEFAULT_CONTENT;const row=await env.DB.prepare(`SELECT value FROM settings WHERE key='content'`).first();if(!row){await env.DB.prepare(`INSERT INTO settings (key,value) VALUES ('content',?)`).bind(JSON.stringify(DEFAULT_CONTENT)).run();return DEFAULT_CONTENT}try{return mergeDefaults(JSON.parse(row.value))}catch{return DEFAULT_CONTENT}}
async function saveContent(request,env){const admin=await requireAdmin(request,env);if(!admin)return json({ok:false,error:'Unauthorized'},401);if(!env.DB)return json({ok:false,error:'D1 binding DB is missing'},500);const body=await request.json().catch(()=>null);if(!body||typeof body!=='object')return json({ok:false,error:'Invalid JSON'},400);const current=await getContent(env);await env.DB.prepare(`INSERT INTO content_versions (id,value,actor) VALUES (?,?,?)`).bind(crypto.randomUUID(),JSON.stringify(current),admin.role||'admin').run();await env.DB.prepare(`INSERT INTO settings (key,value,updated_at) VALUES ('content',?,CURRENT_TIMESTAMP) ON CONFLICT(key) DO UPDATE SET value=excluded.value, updated_at=CURRENT_TIMESTAMP`).bind(JSON.stringify(mergeDefaults(body))).run();await audit(env,request,'content.save');return json({ok:true,version:VERSION})}
async function aiDraft(request,env){const admin=await requireAdmin(request,env);if(!admin)return json({ok:false,error:'Unauthorized'},401);const b=await request.json().catch(()=>({}));const topic=String(b.topic||'Qassem.net').trim().slice(0,500);const tone=String(b.tone||'executive premium').trim().slice(0,120);const type=String(b.type||'bio');const keyword=String(b.keyword||topic).trim().slice(0,140);const map={bio:`${topic} is positioned as a premium executive technology platform for AI, cloud architecture, cybersecurity, and digital transformation. Tone: ${tone}.

Core message:
- Secure systems before flashy features.
- Edge-first performance with measurable business outcomes.
- Clear authority in AI, Cloudflare, cybersecurity, and modern digital operations.`,improve:`Improved version for ${topic}:

Make the message sharper, more specific, and outcome-driven. Replace generic claims with measurable value, simplify long sentences, and keep a confident ${tone} voice.`,project:`${topic} is an enterprise-grade product layer combining a premium dark UI, secure edge backend, D1 data control, R2 media operations, analytics, backup/versioning, and AI-assisted publishing. It is designed to scale without turning the codebase into a fragile demo.`,seo:`SEO Title: ${topic} | AI, Cloud & Cybersecurity Operating System
Meta Description: Explore ${topic}, a fast edge-first platform with secure content operations, premium UX, dynamic SEO, analytics, and AI-assisted publishing.
Primary keyword: ${keyword}
OpenGraph: Premium AI operating dashboard for secure digital systems.`,blog:`# ${topic}

Modern digital platforms are becoming operating systems: content, analytics, media, security, SEO, and AI workflows all need to run from one controlled surface.

## Why it matters
A serious platform needs speed, governance, and a visual identity that communicates trust. Edge-first infrastructure, D1-backed content, R2 media storage, audit logs, and AI-assisted writing turn a simple website into an operational product.

## Practical architecture
Use Cloudflare Pages for delivery, Workers for APIs, D1 for structured data, R2 for durable files, secure sessions for admin access, and snapshots for rollback.`,linkedin:`${topic} blends systems architecture, cloud engineering, cybersecurity, and AI-assisted digital strategy into one clear executive profile. The focus is practical: build secure, fast, elegant systems that improve operations and create measurable outcomes.`};await audit(env,request,'ai.draft',{type});return json({ok:true,type,output:map[type]||map.bio,provider:env.AI?'cloudflare-ai-ready':'local-template',model:env.AI?'workers-ai-ready':'local-enterprise-template-v3'})}
async function mediaRoute(request,env,url){if(!url.pathname.startsWith('/api/media'))return null;if(!env.BUCKET)return json({ok:false,error:'R2 binding BUCKET is missing'},500);await ensureDb(env);if(request.method==='GET'&&url.pathname==='/api/media'){const rows=env.DB?(await env.DB.prepare(`SELECT * FROM media ORDER BY created_at DESC`).all()).results:[];return json({ok:true,media:rows||[]})}if(request.method==='GET'&&url.pathname.startsWith('/api/media/file/')){const key=decodeURIComponent(url.pathname.replace('/api/media/file/',''));const obj=await env.BUCKET.get(key);if(!obj)return text('Not found','text/plain',404);return new Response(obj.body,{headers:{'content-type':obj.httpMetadata?.contentType||'application/octet-stream','cache-control':'public, max-age=31536000, immutable',...SECURITY_HEADERS}})}const admin=await requireAdmin(request,env);if(!admin)return json({ok:false,error:'Unauthorized'},401);if(request.method==='POST'&&url.pathname==='/api/media/upload'){const b=await request.json().catch(()=>null);if(!b?.base64)return json({ok:false,error:'Missing base64 file'},400);const type=String(b.type||'application/octet-stream').slice(0,100);if(!/^(image\/|application\/pdf|text\/plain|application\/msword|application\/vnd.openxmlformats-officedocument)/.test(type))return json({ok:false,error:'File type not allowed'},400);const raw=String(b.base64).split(',').pop();const bytes=Uint8Array.from(atob(raw),c=>c.charCodeAt(0));if(bytes.length>15*1024*1024)return json({ok:false,error:'Max file size is 15MB'},413);const filename=safeName(b.filename), id=crypto.randomUUID(), key=`uploads/${new Date().toISOString().slice(0,10)}/${id}-${filename}`;await env.BUCKET.put(key,bytes,{httpMetadata:{contentType:type,cacheControl:'public, max-age=31536000, immutable'}});const out=env.R2_PUBLIC_URL?`${env.R2_PUBLIC_URL.replace(/\/$/,'')}/${key}`:`/api/media/file/${key}`;if(env.DB)await env.DB.prepare(`INSERT INTO media (id,filename,key,type,size,url,alt) VALUES (?,?,?,?,?,?,?)`).bind(id,filename,key,type,bytes.length,out,String(b.alt||'')).run();await audit(env,request,'media.upload',{filename,type,size:bytes.length});return json({ok:true,file:{id,filename,key,type,size:bytes.length,url:out}})}if(request.method==='DELETE'){const id=decodeURIComponent(url.pathname.split('/').pop());const row=env.DB&&await env.DB.prepare(`SELECT * FROM media WHERE id=?`).bind(id).first();if(!row)return json({ok:false,error:'Media not found'},404);await env.BUCKET.delete(row.key);await env.DB.prepare(`DELETE FROM media WHERE id=?`).bind(id).run();await audit(env,request,'media.delete',{id});return json({ok:true})}return null}
async function seoAnalytics(request,env,url){await ensureDb(env);if(request.method==='POST'&&url.pathname==='/api/analytics/track'){if(!(await rateLimit(env,'track:'+ip(request),120,60)))return json({ok:false,error:'rate_limited'},429);const b=await request.json().catch(()=>({}));if(env.DB)await env.DB.prepare(`INSERT INTO analytics_events (id,path,referrer,user_agent,country) VALUES (?,?,?,?,?)`).bind(crypto.randomUUID(),String(b.path||'/').slice(0,300),String(b.referrer||'').slice(0,500),String(b.userAgent||'').slice(0,500),request.cf?.country||'').run();return json({ok:true})}if(request.method==='GET'&&url.pathname==='/api/admin/analytics'){if(!(await requireAdmin(request,env)))return json({ok:false,error:'Unauthorized'},401);const total=await env.DB.prepare(`SELECT COUNT(*) count FROM analytics_events`).first();const pages=await env.DB.prepare(`SELECT path,COUNT(*) views FROM analytics_events GROUP BY path ORDER BY views DESC LIMIT 20`).all();const countries=await env.DB.prepare(`SELECT country,COUNT(*) views FROM analytics_events WHERE country!='' GROUP BY country ORDER BY views DESC LIMIT 20`).all();const recent=await env.DB.prepare(`SELECT path,country,created_at FROM analytics_events ORDER BY created_at DESC LIMIT 20`).all();return json({ok:true,totalViews:total?.count||0,topPages:pages.results||[],countries:countries.results||[],recent:recent.results||[]})}if(request.method==='GET'&&url.pathname==='/api/seo'){const rows=env.DB?(await env.DB.prepare(`SELECT key,value FROM seo_settings`).all()).results:[];return json({ok:true,seo:Object.fromEntries((rows||[]).map(r=>[r.key,r.value]))})}if(request.method==='POST'&&url.pathname==='/api/admin/seo'){if(!(await requireAdmin(request,env)))return json({ok:false,error:'Unauthorized'},401);const b=await request.json().catch(()=>({}));for(const [k,v]of Object.entries(b))await env.DB.prepare(`INSERT INTO seo_settings (key,value,updated_at) VALUES (?,?,CURRENT_TIMESTAMP) ON CONFLICT(key) DO UPDATE SET value=excluded.value, updated_at=CURRENT_TIMESTAMP`).bind(k,String(v||'')).run();await audit(env,request,'seo.save');return json({ok:true})}if(url.pathname==='/robots.txt')return text(`User-agent: *
Allow: /
Sitemap: ${url.origin}/sitemap.xml
`);if(url.pathname==='/sitemap.xml'){const content=await getContent(env);const urls=['/'];for(const p of content.projects||[])if(p.url)urls.push(p.url);for(const p of content.blog||[])if(p.slug)urls.push('/blog/'+p.slug);const xml=`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${[...new Set(urls)].map(p=>`<url><loc>${url.origin}${p.startsWith('/')?p:'/'+p}</loc><lastmod>${new Date().toISOString().slice(0,10)}</lastmod></url>`).join('')}</urlset>`;return text(xml,'application/xml; charset=utf-8')}return null}
async function backup(request,env,url){if(!url.pathname.startsWith('/api/admin/backup')&&!url.pathname.startsWith('/api/admin/snapshots'))return null;const admin=await requireAdmin(request,env);if(!admin)return json({ok:false,error:'Unauthorized'},401);await ensureDb(env);if(url.pathname==='/api/admin/snapshots'&&request.method==='GET'){const rows=(await env.DB.prepare(`SELECT id,label,created_at,actor FROM snapshots ORDER BY created_at DESC LIMIT 40`).all()).results||[];return json({ok:true,snapshots:rows})}if(url.pathname==='/api/admin/snapshots'&&request.method==='POST'){const b=await request.json().catch(()=>({}));await env.DB.prepare(`INSERT INTO snapshots (id,label,value,actor) VALUES (?,?,?,?)`).bind(crypto.randomUUID(),String(b.label||'Manual snapshot').slice(0,120),JSON.stringify(await getContent(env)),admin.role||'admin').run();await audit(env,request,'snapshot.create');return json({ok:true})}if(url.pathname.match(/\/api\/admin\/snapshots\/[^/]+\/restore$/)&&request.method==='POST'){const id=url.pathname.split('/')[4];const row=await env.DB.prepare(`SELECT value FROM snapshots WHERE id=?`).bind(id).first();if(!row)return json({ok:false,error:'Snapshot not found'},404);await env.DB.prepare(`INSERT INTO settings (key,value,updated_at) VALUES ('content',?,CURRENT_TIMESTAMP) ON CONFLICT(key) DO UPDATE SET value=excluded.value, updated_at=CURRENT_TIMESTAMP`).bind(row.value).run();await audit(env,request,'snapshot.restore',{id});return json({ok:true})}if(url.pathname.endsWith('/export')){const tables={};for(const t of ['settings','content_versions','snapshots','media','analytics_events','seo_settings','audit_logs','security_settings'])tables[t]=(await env.DB.prepare(`SELECT * FROM ${t}`).all()).results||[];return json({app:'qassem-dashboard',version:VERSION,exportedAt:nowIso(),tables},200,{'content-disposition':`attachment; filename="qassem-backup-${new Date().toISOString().slice(0,10)}.json"`})}if(url.pathname.endsWith('/import')&&request.method==='POST'){const b=await request.json().catch(()=>null);if(!b?.tables)return json({ok:false,error:'Invalid backup'},400);for(const row of b.tables.settings||[])if(row.key&&row.value)await env.DB.prepare(`INSERT INTO settings (key,value,updated_at) VALUES (?,?,CURRENT_TIMESTAMP) ON CONFLICT(key) DO UPDATE SET value=excluded.value, updated_at=CURRENT_TIMESTAMP`).bind(row.key,row.value).run();for(const row of b.tables.seo_settings||[])if(row.key&&row.value)await env.DB.prepare(`INSERT INTO seo_settings (key,value,updated_at) VALUES (?,?,CURRENT_TIMESTAMP) ON CONFLICT(key) DO UPDATE SET value=excluded.value, updated_at=CURRENT_TIMESTAMP`).bind(row.key,row.value).run();await audit(env,request,'backup.import');return json({ok:true})}return null}
async function securityRoute(request,env,url){if(!url.pathname.startsWith('/api/admin/security'))return null;if(!(await requireAdmin(request,env)))return json({ok:false,error:'Unauthorized'},401);await ensureDb(env);if(url.pathname.endsWith('/audit')){const rows=(await env.DB.prepare(`SELECT action,metadata,ip,user_agent,created_at FROM audit_logs ORDER BY created_at DESC LIMIT 100`).all()).results||[];return json({ok:true,logs:rows})}if(url.pathname.endsWith('/sessions')){const rows=(await env.DB.prepare(`SELECT id,role,expires_at,revoked_at,ip,user_agent,created_at FROM sessions ORDER BY created_at DESC LIMIT 50`).all()).results||[];return json({ok:true,sessions:rows})}return null}

function abosDemoSnapshot(){const now=Date.now(),day=86400000;return{generatedAt:new Date().toISOString(),projects:[{id:'p1',title:'Enterprise Client Onboarding',status:'active',deadline:new Date(now+5*day).toISOString(),revenueImpact:120000},{id:'p2',title:'Automation Workflow Rollout',status:'active',deadline:new Date(now+14*day).toISOString(),revenueImpact:80000},{id:'p3',title:'Quarterly Revenue Recovery',status:'at_risk',deadline:new Date(now+8*day).toISOString(),revenueImpact:210000}],tasks:[{id:'t1',projectId:'p1',status:'blocked',priority:'critical',assignedTo:'Maya',dueDate:new Date(now-2*day).toISOString(),dependencies:['crm-export']},{id:'t2',projectId:'p1',status:'in_progress',priority:'high',assignedTo:'Maya',dueDate:new Date(now+day).toISOString(),dependencies:['legal']},{id:'t3',projectId:'p2',status:'in_progress',priority:'high',assignedTo:'Omar',dueDate:new Date(now+3*day).toISOString()},{id:'t4',projectId:'p3',status:'blocked',priority:'critical',assignedTo:'Maya',dueDate:new Date(now-day).toISOString(),dependencies:['pricing-approval']}],activities:[{id:'a1',entityType:'project',entityId:'p1',action:'Migration blocked by missing CRM export',severity:'critical',createdAt:new Date().toISOString()}]}}
function abosRiskEngine(snapshot=abosDemoSnapshot()){const now=Date.now(),priority={low:4,medium:9,high:16,critical:26};const risks=snapshot.projects.map(project=>{const tasks=snapshot.tasks.filter(task=>task.projectId===project.id&&task.status!=='done');const overdue=tasks.filter(task=>new Date(task.dueDate).getTime()<now);const blocked=tasks.filter(task=>task.status==='blocked');const load=tasks.reduce((sum,task)=>sum+(priority[task.priority]||9),0);const daysToDeadline=Math.ceil((new Date(project.deadline).getTime()-now)/86400000);const score=clamp(12+overdue.length*15+blocked.length*18+load+Math.max(0,18-daysToDeadline)*2,0,100);return{id:`risk-${project.id}`,projectId:project.id,title:`${project.title} delay probability is ${score}%`,score,severity:score>=82?'critical':score>=64?'high':score>=38?'medium':'low',recommendation:'Escalate blocked tasks, assign one owner per dependency, and reduce scope within 24 hours.',evidence:[`${overdue.length} overdue task(s)`,`${blocked.length} blocked task(s)`,`Deadline: ${project.deadline}`]}}).filter(risk=>risk.score>=38).sort((a,b)=>b.score-a.score);const averageRisk=risks.reduce((sum,risk)=>sum+risk.score,0)/Math.max(1,risks.length);return{ok:true,product:'ABOS Cortex V1',generatedAt:new Date().toISOString(),operationalHealth:clamp(100-averageRisk*.6,0,100),revenueAtRisk:Math.round(risks.reduce((sum,risk)=>{const project=snapshot.projects.find(item=>item.id===risk.projectId);return sum+(project?.revenueImpact||0)*(risk.score/100)},0)),risks,nextBestActions:risks.slice(0,3).map(risk=>risk.recommendation)}}

export default {async fetch(request,env){const url=new URL(request.url);try{await ensureDb(env);if(url.pathname==='/api/auth/login'||url.pathname==='/api/admin/login'){if(request.method!=='POST')return json({ok:false,error:'Method not allowed'},405);if(!(await rateLimit(env,'login:'+ip(request),8,300)))return json({ok:false,error:'Too many attempts'},429);const b=await request.json().catch(()=>({}));if(!adminPassword(env))return json({ok:false,error:'ADMIN_PASSWORD is missing'},500);if(b.password!==adminPassword(env)){await audit(env,request,'auth.failed');return json({ok:false,error:'Invalid password'},401)}const token=await createToken(env,request);await audit(env,request,'auth.login');return json({ok:true,token,expiresInHours:12,twoFactorReady:true},200,{'set-cookie':`qassem_session=${token}; HttpOnly; Secure; SameSite=Strict; Path=/; Max-Age=43200`})}if(url.pathname==='/api/auth/logout'){const auth=(request.headers.get('authorization')||'').replace(/^Bearer\s+/i,'').trim();const p=await verifyToken(auth,env);if(p?.sid&&env.DB)await env.DB.prepare(`UPDATE sessions SET revoked_at=? WHERE id=?`).bind(Date.now(),p.sid).run();return json({ok:true},200,{'set-cookie':'qassem_session=deleted; Path=/; Max-Age=0'})}if(url.pathname==='/api/auth/check')return (await requireAdmin(request,env))?json({ok:true,version:VERSION}):json({ok:false},401);if(url.pathname==='/api/content'&&request.method==='GET')return json(await getContent(env));if(url.pathname==='/api/abos/health'||url.pathname==='/api/abos/risks')return json(abosRiskEngine());if(url.pathname==='/api/admin/content'&&request.method==='POST')return saveContent(request,env);if(url.pathname==='/api/admin/ai/draft'&&request.method==='POST')return aiDraft(request,env);let r=await mediaRoute(request,env,url);if(r)return r;r=await seoAnalytics(request,env,url);if(r)return r;r=await backup(request,env,url);if(r)return r;r=await securityRoute(request,env,url);if(r)return r;if(url.pathname.startsWith('/api/'))return json({ok:false,error:'Not found'},404);return withSecurity(await env.ASSETS.fetch(request))}catch(e){return json({ok:false,error:e.message||String(e),version:VERSION},500)}}};
